// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvA-f_2nytKoGT7LlcPl6KwCn4k-9wxYs',
    appId: '1:500783748544:web:6a5b5bdb2308bd65566425',
    messagingSenderId: '500783748544',
    projectId: 'desafiosilicon-caee3',
    authDomain: 'desafiosilicon-caee3.firebaseapp.com',
    storageBucket: 'desafiosilicon-caee3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGw79xP1Le6vD5OtKO4aOVicOEr_UPeL0',
    appId: '1:500783748544:android:f0dbe5b19ee85b57566425',
    messagingSenderId: '500783748544',
    projectId: 'desafiosilicon-caee3',
    storageBucket: 'desafiosilicon-caee3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdJigiCyWnsg5-SqIJXxuQhajioPpM_ds',
    appId: '1:500783748544:ios:aa507ce08b7c9d0a566425',
    messagingSenderId: '500783748544',
    projectId: 'desafiosilicon-caee3',
    storageBucket: 'desafiosilicon-caee3.appspot.com',
    iosClientId: '500783748544-0j3vc6bs1chum3j8gm94sjpf4q9jofrs.apps.googleusercontent.com',
    iosBundleId: 'com.example.desafioSilicon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdJigiCyWnsg5-SqIJXxuQhajioPpM_ds',
    appId: '1:500783748544:ios:aa507ce08b7c9d0a566425',
    messagingSenderId: '500783748544',
    projectId: 'desafiosilicon-caee3',
    storageBucket: 'desafiosilicon-caee3.appspot.com',
    iosClientId: '500783748544-0j3vc6bs1chum3j8gm94sjpf4q9jofrs.apps.googleusercontent.com',
    iosBundleId: 'com.example.desafioSilicon',
  );
}
